### ISSUE TITLE
Update dicomViewer on npmjs.com

### ISSUE THREAD

**Issue by Nushio** [fourctv/dicomViewerLib#1]
Hi there! Could you update the package on npmjs.com to support Angular 8?

Thanks!

**Comment by fourctv** [comment]
That was done about 2 weeks ago. Support now is to Ng 8.1.3

**Comment by fourctv** [comment]
Sorry Juan, I misunderstood your request. I had updated the package but forgot to publish to npm. Done.

**Comment by Nushio** [comment]
No problem. Thanks for updating the package!
