### ISSUE TITLE
 import { DICOMViewerComponent } from 'dicomViewer';

### ISSUE THREAD

**Issue by GCPBigData** [fourctv/dicomViewerLib#17]
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'dicomViewer' in '/home/junior/dev/@Angular/dicomViewerLib/src/app'
    
    ERROR in src/app/app.component.ts:2:38 - error TS2307: Cannot find module 'dicomViewer' or its corresponding type declarations.
    
    2 import { DICOMViewerComponent } from 'dicomViewer';
                                           ~~~~~~~~~~~~~
    src/app/app.module.ts:9:35 - error TS2307: Cannot find module 'dicomViewer' or its corresponding type declarations.
    
    9 import { DicomViewerModule } from 'dicomViewer';

**Comment by Carlycode** [comment]
try:

import { DicomViewerModule } from 'ng-dicomviewer';

**Comment by fourctv** [comment]
Exactly @Carlycode.
Thanks for the comment.
