### ISSUE TITLE
Feature needed

### ISSUE THREAD

**Issue by arunjoshtech** [fourctv/dicomViewerLib#22]
Dear sir,
I am impressed with your work on this project, Kindly implement MPR basic version to really successful project.

**Comment by fourctv** [comment]
What do you mean by "MPR basic version"?

**Comment by arunjoshtech** [comment]
MPR options like OHIF viewer has implemented using vtkjs.it will makes this angular meaningful and it worth. Kindly work on it to make this project more usable.
