### ISSUE TITLE
Next/Previous Image buttons (in toolbar) not working for few anonymized DICOM files

### ISSUE THREAD

**Issue by vnngoc156** [fourctv/dicomViewerLib#3]
For anonymized DICOM files in which patient name metadata is removed completely (not just replaced by another anonymized name string), the next/previous image buttons do not work as expected. This is happening because the code to display an image (in cornerstone.directive.ts) always treats patient name as non-empty and apply a string operation on that. Patient name metadata should be checked for non-empty string before applying any operation on it.

**Comment by fourctv** [comment]
can you provide some samples to reproduce it.
from your description it seems to be an issue with cornerstone or cornersstoneTools, and should be reported there.

**Comment by vnngoc156** [comment]
Please download the sample dicom file from [here](https://drive.google.com/open?id=1xxnujIIoLq5SNMvGr7rC0iP2wCOagKxu) (too big to attached directly). The file has patient name tag emptied using DICOM Anonymizer tool from [http://www.dicomapps.com/](http://www.dicomapps.com/)

**Comment by fourctv** [comment]
@vnngoc156, that dicom file is an image video and the demo app included here does not support playing videos.
The next/previous buttons are for navigating thru images in a Series. If you select multiple images in the same Series, then you can use next/previous buttons.
Likewise, the Play/Stop buttons are for automatically navigate thru multiple images within the same Series.
