### ISSUE TITLE
Compatibility for Angular 9

### ISSUE THREAD

**Issue by abdullegend** [fourctv/dicomViewerLib#6]
Dear Fourctv,
Will this package can be used in angular 9?
Advise on it, because of ivy rendering in angular 9 I feel it will perform better.kindly advise.

**Comment by fourctv** [comment]
I have not tried it yet, but the library should work with NG 9, as I have other NG 8 libraries that work find with Angular 9.

At this point I have no bandwith to update this library. And first priority here would be to update it to the latest conerstoneTools first. When I get a break I'll look into that.

**Comment by abdullegend** [comment]
Thanks for the reply and looking forward for your greatest work on this.
May I know your schedule regarding cornerstone Tools update?

**Comment by fourctv** [comment]
Posted yesterday a newer version that is compatible with Angular 9.
Updated all other dependencies as well, and upgraded to cornerstoneTools v4.
